const teste = {
_failureText: 'net::ERR_ABORTED',
_response: HTTPResponse {
    _contentPromise: null,
_headers: {
        'access-control-allow-origin': 'https://web.whatsapp.com';,
        'access-control-expose-headers': 'X-FB-Debug',
'content-length': '0',
date: 'Wed, 28 Jun 2023 22:17:09 GMT',
'x-fb-application-protocol': 'h2'
},
    _client: CDPSession {
        eventsMap: [Map],
emitter: [Object],
_callbacks: [Map],
_connection: [Connection],
_targetType: 'page',
_sessionId: 'B8B92B650609861D4B3FAB496F8891D3'
},
    _request: [Circular *1],
_bodyLoadedPromiseFulfill: [Function (anonymous)],
_bodyLoadedPromise: Promise { null },
    _remoteAddress: { ip: '117.205.230.162', port: 443 },
    _statusText: '',
_url: 'https://media.fmaa10-1.fna.whatsapp.net/mms/image/AyrOVaR2sXbOdG0BayLTUAhQnV6uY0wH6G_WBu4bu5s=?token=AyrOVaR2sXbOdG0BayLTUAhQnV6uY0wH6G_WBu4bu5s%3D&d_md=L3YvdDYyLjMxMTExLTI0LzMyMzQxODQ2Xzk3MzE5MTU5MDM5MTY4NF82MDY1MDA2MDc0OTA1NDQ4NzMwX24uZW5j&auth=AWRbVbQXCgWjesLqg1MpuSg5Z6bxTmX8N8HYO8xPkDhNcwCMFOykHcCiCL0';,
    _fromDiskCache: false,
_fromServiceWorker: false,
_status: 200,
_securityDetails: SecurityDetails {
        _subjectName: '*.fmaa10-1.fna.whatsapp.net',
_issuer: 'DigiCert SHA2 High Assurance Server CA',
_validFrom: 1686268800,
_validTo: 1694131199,
_protocol: 'TLS 1.3',
_sanList: [Array]
},
    _timing: {
        requestTime: 505041.403096,
proxyStart: -1,
proxyEnd: -1,
dnsStart: -1,
dnsEnd: -1,
connectStart: -1,
connectEnd: -1,
sslStart: -1,
sslEnd: -1,
workerStart: -685.059,
workerReady: -684.948,
workerFetchStart: -1,
workerRespondWithSettled: -1,
sendStart: 0.647,
sendEnd: 0.795,
pushStart: 0,
pushEnd: 0,
receiveHeadersEnd: 784.565
}
},
_fromMemoryCache: false,
_interceptionHandled: false,
_headers: {
    referer: 'https://web.whatsapp.com/';,
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36'
},
_client: CDPSession {
    eventsMap: Map(30) {
        'Fetch.requestPaused' => [Array],
'Fetch.authRequired' => [Array],
'Network.requestWillBeSent' => [Array],
'Network.requestServedFromCache' => [Array],
'Network.responseReceived' => [Array],
'Network.loadingFinished' => [Array],
'Network.loadingFailed' => [Array],
'Network.responseReceivedExtraInfo' => [Array],
'Page.frameAttached' => [Array],
'Page.frameNavigated' => [Array],
'Page.navigatedWithinDocument' => [Array],
'Page.frameDetached' => [Array],
'Page.frameStoppedLoading' => [Array],
'Runtime.executionContextCreated' => [Array],
'Runtime.executionContextDestroyed' => [Array],
'Runtime.executionContextsCleared' => [Array],
'Page.lifecycleEvent' => [Array],
'Target.attachedToTarget' => [Array],
'Target.detachedFromTarget' => [Array],
'Page.domContentEventFired' => [Array],
'Page.loadEventFired' => [Array],
'Runtime.consoleAPICalled' => [Array],
'Runtime.bindingCalled' => [Array],
'Page.javascriptDialogOpening' => [Array],
'Runtime.exceptionThrown' => [Array],
'Inspector.targetCrashed' => [Array],
'Performance.metrics' => [Array],
'Log.entryAdded' => [Array],
'Page.fileChooserOpened' => [Array],
Symbol(CDPSession.Disconnected) => []
},
    emitter: {
        all: [Map],
on: [Function: on],
        off: [Function: off],
        emit: [Function: emit]
        },
    _callbacks: Map(1) { 59 => [Object] },
    _connection: Connection {
        eventsMap: [Map],
emitter: [Object],
_lastId: 59,
_sessions: [Map],
_closed: false,
_callbacks: Map(0) {},
        _url: 'ws://127.0.0.1:44753/devtools/browser/846eb23d-d02a-41d5-8e20-5879c5786d8a',
_delay: 0,
_transport: [NodeWebSocketTransport]
},
    _targetType: 'page',
_sessionId: 'B8B92B650609861D4B3FAB496F8891D3'
},
_requestId: '42.363',
_isNavigationRequest: false,
_interceptionId: null,
_allowInterception: false,
_url: 'https://media.fmaa10-1.fna.whatsapp.net/mms/image/AyrOVaR2sXbOdG0BayLTUAhQnV6uY0wH6G_WBu4bu5s=?token=AyrOVaR2sXbOdG0BayLTUAhQnV6uY0wH6G_WBu4bu5s%3D&d_md=L3YvdDYyLjMxMTExLTI0LzMyMzQxODQ2Xzk3MzE5MTU5MDM5MTY4NF82MDY1MDA2MDc0OTA1NDQ4NzMwX24uZW5j&auth=AWRbVbQXCgWjesLqg1MpuSg5Z6bxTmX8N8HYO8xPkDhNcwCMFOykHcCiCL0';,
_resourceType: 'fetch',
_method: 'DELETE',
_postData: undefined,
}